In [1]:
import sys
MODULEPATH="../../"
sys.path.append(MODULEPATH)
sys.path.append('../')
from connectivity.plot_results import plot_results_with_paths, plot_saddle_tree_with_function, plot_full_connectivity_tree_style

from critical_points.torch_critical_point_finder import find_critical_points_torch, save_critical_points_to_csv
from test_schwefel.schwefel_function_nnmodule import Schwefel3D, schwefel_loss  # your existing module

import matplotlib.pyplot as plt
import pandas as pd

In [2]:
model_builder = lambda p: Schwefel3D(*p)

In [3]:
# Set parameters
BOUNDS = {'x1': (0.0, 1.0), 'x2': (0.0, 1.0), 'x3': (0.0, 1.0)}
DIM = 3
ATTEMPTS = 1024
MIN_DISTANCE = 0.01

In [4]:
try:
    resume_df = pd.read_csv("critical_points_schwefel_3D.csv", index_col=0)
    resume_df = resume_df[resume_df['type']=='minimum']
    display(resume_df)
except FileNotFoundError:
    resume_df = None

          x1        x2        x3       f_value     type
0   0.341809  0.824375  0.824375  2.171397e-01  minimum
1   0.034551  0.034551  0.034551  1.066044e+00  minimum
2   0.034551  0.034551  0.824375  7.106958e-01  minimum
3   0.341809  0.341809  0.341809  6.514190e-01  minimum
4   0.034551  0.824375  0.824375  3.553479e-01  minimum
5   0.341809  0.034551  0.034551  9.278355e-01  minimum
6   0.034551  0.824375  0.034551  7.106958e-01  minimum
7   0.824375  0.341809  0.824375  2.171397e-01  minimum
8   0.341809  0.341809  0.034551  7.896273e-01  minimum
9   0.824375  0.341809  0.341809  4.342794e-01  minimum
10  0.824375  0.824375  0.034551  3.553479e-01  minimum
11  0.341809  0.824375  0.341809  4.342794e-01  minimum
12  0.824375  0.824375  0.341809  2.171397e-01  minimum
13  0.341809  0.341809  0.824375  4.342794e-01  minimum
14  0.034551  0.341809  0.824375  5.724876e-01  minimum
15  0.034551  0.034551  0.341809  9.278355e-01  minimum
16  0.034551  0.341809  0.341809  7.896273e-01  minimum
17  0.824375  0.341809  0.034551  5.724876e-01  minimum
18  0.341809  0.034551  0.824375  5.724876e-01  minimum
19  0.824375  0.824375  0.824375  3.820000e-08  minimum
20  0.034551  0.824375  0.341809  5.724876e-01  minimum
21  0.341809  0.034551  0.341809  7.896273e-01  minimum
22  0.824375  0.034551  0.034551  7.106958e-01  minimum
23  0.341809  0.824375  0.034551  5.724876e-01  minimum
24  0.824375  0.034551  0.341809  5.724876e-01  minimum
25  0.824375  0.034551  0.824375  3.553479e-01  minimum
26  0.034551  0.341810  0.034551  9.278355e-01  minimum

In [5]:
minima, maxima, saddles = find_critical_points_torch(
    model_builder=model_builder,
    minima_only=True,
    loss_func=schwefel_loss,
    input = [],             # placeholder model input for compatibility (Schwefel model has no model input)
    bounds=BOUNDS,
    dimension=DIM,
    num_attempts=ATTEMPTS,
    min_distance=MIN_DISTANCE,
    device="cpu",
    lr=5e-2,
    max_iter=5_000,
    resume_df=resume_df,  # 👈 here!
    seed=1101
)

Loaded 27 valid points from dataframe.
Resuming with 27 loaded points.

__________________________________________________________________________________________
Attempt 1/1024:
Starting point: [0.25317813 0.88321528 0.5628975 ]
Arrival point: [0.34180722 0.8243742  0.82437393]
check grad: tensor([-1.1508e-04, -4.0400e-05, -5.4370e-05])
tensor(0.0001)
Converged to critical point with ||grad||=1.34e-04 < 1e-05
Point [0.34180722 0.8243742  0.82437393] is too close to existing minimum at [0.34180945 0.82437499 0.82437499] (distance 0.000003 < 0.01)
Point [0.34180722 0.8243742  0.82437393] is too close to existing minimum. Rejecting.

__________________________________________________________________________________________
Attempt 2/1024:
Starting point: [0.77770659 0.06539727 0.25324407]
Arrival point: [0.82437224 0.03455237 0.34180911]
check grad: tensor([-1.4061e-04,  8.3701e-05, -1.7317e-05])
tensor(0.0002)
Converged to critical point with ||grad||=1.65e-04 < 1e-05
Point [0.82437224 0.03455237 0.34180911] is too close to existing minimum at [0.82437499 0.03455081 0.34180945] (distance 0.000003 < 0.01)
Point [0.82437224 0.03455237 0.34180911] is too close to existing minimum. Rejecting.

__________________________________________________________________________________________
Attempt 3/1024:
Starting point: [0.56835509 0.56319261 0.84452757]
Arrival point: [0.82437732 0.82437449 0.82437549]
check grad: tensor([ 1.1903e-04, -2.5810e-05,  2.5577e-05])
tensor(0.0001)
Converged to critical point with ||grad||=1.24e-04 < 1e-05
Point [0.82437732 0.82437449 0.82437549] is too close to existing minimum at [0.82437499 0.82437499 0.82437499] (distance 0.000002 < 0.01)
Point [0.82437732 0.82437449 0.82437549] is too close to existing minimum. Rejecting.

__________________________________________________________________________________________
Attempt 4/1024:
Starting point: [0.08874842 0.38493165 0.03510112]
Arrival point: [0.03455251 0.34181347 0.03455087]
check grad: tensor([9.1299e-05, 2.0722e-04, 3.3414e-06])
tensor(0.0002)
Converged to critical point with ||grad||=2.26e-04 < 1e-05
Point [0.03455251 0.34181347 0.03455087] is too close to existing minimum at [0.03455085 0.34180952 0.03455079] (distance 0.000004 < 0.01)
Point [0.03455251 0.34181347 0.03455087] is too close to existing minimum. Rejecting.

__________________________________________________________________________________________
Attempt 5/1024:
Starting point: [0.1467218  0.65715037 0.38284267]
Arrival point: [0.03455174 0.82437725 0.3418091 ]
check grad: tensor([ 4.9842e-05,  1.1518e-04, -1.8211e-05])
tensor(0.0001)
Converged to critical point with ||grad||=1.27e-04 < 1e-05
Point [0.03455174 0.82437725 0.3418091 ] is too close to existing minimum at [0.0345508  0.82437499 0.34180942] (distance 0.000002 < 0.01)
Point [0.03455174 0.82437725 0.3418091 ] is too close to existing minimum. Rejecting.

__________________________________________________________________________________________
Attempt 6/1024:
Starting point: [0.63391115 0.35395075 0.69847755]
Arrival point: [0.82437282 0.3418089  0.82437651]
check grad: tensor([-1.1088e-04, -2.8617e-05,  7.7379e-05])
tensor(0.0001)
Converged to critical point with ||grad||=1.38e-04 < 1e-05
Point [0.82437282 0.3418089  0.82437651] is too close to existing minimum at [0.82437499 0.34180945 0.82437499] (distance 0.000003 < 0.01)
Point [0.82437282 0.3418089  0.82437651] is too close to existing minimum. Rejecting.

__________________________________________________________________________________________
Attempt 7/1024:
Starting point: [0.95362088 0.85174561 0.16468831]
Arrival point: [0.82437355 0.82437299 0.03455174]
check grad: tensor([-7.3772e-05, -1.0213e-04,  5.0072e-05])
tensor(0.0001)
Converged to critical point with ||grad||=1.36e-04 < 1e-05
Point [0.82437355 0.82437299 0.03455174] is too close to existing minimum at [0.824375   0.82437499 0.03455081] (distance 0.000003 < 0.01)
Point [0.82437355 0.82437299 0.03455174] is too close to existing minimum. Rejecting.

__________________________________________________________________________________________
Attempt 8/1024:
Starting point: [0.45275785 0.15886722 0.98009621]
Arrival point: [0.34180789 0.03455138 0.82437235]
check grad: tensor([-8.0681e-05,  3.0295e-05, -1.3501e-04])
tensor(0.0002)
Converged to critical point with ||grad||=1.60e-04 < 1e-05
Point [0.34180789 0.03455138 0.82437235] is too close to existing minimum at [0.34180946 0.03455081 0.82437499] (distance 0.000003 < 0.01)
Point [0.34180789 0.03455138 0.82437235] is too close to existing minimum. Rejecting.

__________________________________________________________________________________________
Attempt 9/1024:
Starting point: [0.38030004 0.54317989 0.19915363]
Arrival point: [0.3418088  0.34180879 0.34180676]
check grad: tensor([-3.3564e-05, -3.3925e-05, -1.3879e-04])
tensor(0.0001)
Converged to critical point with ||grad||=1.47e-04 < 1e-05
Point [0.3418088  0.34180879 0.34180676] is too close to existing minimum at [0.34180946 0.34180945 0.34180945] (distance 0.000003 < 0.01)
Point [0.3418088  0.34180879 0.34180676] is too close to existing minimum. Rejecting.

__________________________________________________________________________________________
Attempt 10/1024:
Starting point: [0.90083079 0.47525524 0.88362395]
Arrival point: [0.82437264 0.34181197 0.82437291]
check grad: tensor([-0.0001,  0.0001, -0.0001])
tensor(0.0002)
Converged to critical point with ||grad||=2.07e-04 < 1e-05
Point [0.82437264 0.34181197 0.82437291] is too close to existing minimum at [0.82437499 0.34180945 0.82437499] (distance 0.000004 < 0.01)
Point [0.82437264 0.34181197 0.82437291] is too close to existing minimum. Rejecting.

__________________________________________________________________________________________
Attempt 11/1024:
Starting point: [0.69123316 0.97355412 0.47978604]
Arrival point: [0.82437717 0.82437201 0.34181184]
check grad: tensor([ 0.0001, -0.0002,  0.0001])
tensor(0.0002)
Converged to critical point with ||grad||=2.25e-04 < 1e-05
Point [0.82437717 0.82437201 0.34181184] is too close to existing minimum at [0.82437499 0.82437499 0.34180945] (distance 0.000004 < 0.01)
Point [0.82437717 0.82437201 0.34181184] is too close to existing minimum. Rejecting.

__________________________________________________________________________________________
Attempt 12/1024:
Starting point: [0.21562437 0.04536929 0.66451768]
Arrival point: [0.34180677 0.03454985 0.82437469]
check grad: tensor([-1.3833e-04, -5.1738e-05, -1.5615e-05])
tensor(0.0001)
Converged to critical point with ||grad||=1.49e-04 < 1e-05
Point [0.34180677 0.03454985 0.82437469] is too close to existing minimum at [0.34180946 0.03455081 0.82437499] (distance 0.000003 < 0.01)
Point [0.34180677 0.03454985 0.82437469] is too close to existing minimum. Rejecting.

__________________________________________________________________________________________
Attempt 13/1024:
Starting point: [0.01569466 0.75458827 0.7534226 ]
Arrival point: [0.03455019 0.824373   0.824373  ]
check grad: tensor([-3.3575e-05, -1.0180e-04, -1.0199e-04])
tensor(0.0001)
Converged to critical point with ||grad||=1.48e-04 < 1e-05
Point [0.03455019 0.824373   0.824373  ] is too close to existing minimum at [0.03455081 0.82437499 0.82437499] (distance 0.000003 < 0.01)
Point [0.03455019 0.824373   0.824373  ] is too close to existing minimum. Rejecting.

__________________________________________________________________________________________
Attempt 14/1024:
Starting point: [0.51469612 0.20134306 0.06321497]
Arrival point: [0.34180707 0.34181203 0.03454863]
check grad: tensor([-0.0001,  0.0001, -0.0001])
tensor(0.0002)
Converged to critical point with ||grad||=2.16e-04 < 1e-05
Point [0.34180707 0.34181203 0.03454863] is too close to existing minimum at [0.34180945 0.34180945 0.03455081] (distance 0.000004 < 0.01)
Point [0.34180707 0.34181203 0.03454863] is too close to existing minimum. Rejecting.

__________________________________________________________________________________________
Attempt 15/1024:
Starting point: [0.83464626 0.69964147 0.53431254]
Arrival point: [0.82437443 0.82437918 0.34180899]
check grad: tensor([-2.8518e-05,  2.1425e-04, -2.3857e-05])
tensor(0.0002)
Converged to critical point with ||grad||=2.17e-04 < 1e-05
Point [0.82437443 0.82437918 0.34180899] is too close to existing minimum at [0.82437499 0.82437499 0.34180945] (distance 0.000004 < 0.01)
Point [0.82437443 0.82437918 0.34180899] is too close to existing minimum. Rejecting.

__________________________________________________________________________________________
Attempt 16/1024:
Starting point: [0.32197475 0.25677815 0.3438436 ]
Arrival point: [0.34180873 0.34180651 0.34180952]
check grad: tensor([-3.7100e-05, -1.5167e-04,  3.5035e-06])
tensor(0.0002)
Converged to critical point with ||grad||=1.56e-04 < 1e-05
Point [0.34180873 0.34180651 0.34180952] is too close to existing minimum at [0.34180946 0.34180945 0.34180945] (distance 0.000003 < 0.01)
Point [0.34180873 0.34180651 0.34180952] is too close to existing minimum. Rejecting.

__________________________________________________________________________________________
Attempt 17/1024:
Starting point: [0.3554423  0.74409335 0.91529969]
Arrival point: [0.34181012 0.82437303 0.82437733]
check grad: tensor([ 3.4642e-05, -1.0049e-04,  1.1958e-04])
tensor(0.0002)
Converged to critical point with ||grad||=1.60e-04 < 1e-05
Point [0.34181012 0.82437303 0.82437733] is too close to existing minimum at [0.34180945 0.82437499 0.82437499] (distance 0.000003 < 0.01)
Point [0.34181012 0.82437303 0.82437733] is too close to existing minimum. Rejecting.

__________________________________________________________________________________________
Attempt 18/1024:
Starting point: [0.86416311 0.30022259 0.2289964 ]
Arrival point: [0.82437271 0.3418112  0.34180826]
check grad: tensor([-1.1668e-04,  9.0264e-05, -6.1218e-05])
tensor(0.0002)
Converged to critical point with ||grad||=1.60e-04 < 1e-05
Point [0.82437271 0.3418112  0.34180826] is too close to existing minimum at [0.82437499 0.34180945 0.34180945] (distance 0.000003 < 0.01)
Point [0.82437271 0.3418112  0.34180826] is too close to existing minimum. Rejecting.

__________________________________________________________________________________________
Attempt 19/1024:
Starting point: [0.54421546 0.79803319 0.634673  ]
Arrival point: [0.34181029 0.82437384 0.82437725]
check grad: tensor([ 4.3375e-05, -5.8738e-05,  1.1564e-04])
tensor(0.0001)
Converged to critical point with ||grad||=1.37e-04 < 1e-05
Point [0.34181029 0.82437384 0.82437725] is too close to existing minimum at [0.34180945 0.82437499 0.82437499] (distance 0.000003 < 0.01)
Point [0.34181029 0.82437384 0.82437725] is too close to existing minimum. Rejecting.

__________________________________________________________________________________________
Attempt 20/1024:
Starting point: [0.04916734 0.24579446 0.44811222]
Arrival point: [0.03454984 0.34180668 0.34180921]
check grad: tensor([-5.2026e-05, -1.4292e-04, -1.2363e-05])
tensor(0.0002)
Converged to critical point with ||grad||=1.53e-04 < 1e-05
Point [0.03454984 0.34180668 0.34180921] is too close to existing minimum at [0.03455081 0.34180945 0.34180945] (distance 0.000003 < 0.01)
Point [0.03454984 0.34180668 0.34180921] is too close to existing minimum. Rejecting.

__________________________________________________________________________________________
Attempt 21/1024:
Starting point: [0.24855823 0.95455187 0.09489264]
Arrival point: [0.34180639 0.82437608 0.0345513 ]
check grad: tensor([-1.5816e-04,  5.5683e-05,  2.6355e-05])
tensor(0.0002)
Converged to critical point with ||grad||=1.70e-04 < 1e-05
Point [0.34180639 0.82437608 0.0345513 ] is too close to existing minimum at [0.34180945 0.82437499 0.03455083] (distance 0.000003 < 0.01)
Point [0.34180639 0.82437608 0.0345513 ] is too close to existing minimum. Rejecting.

__________________________________________________________________________________________
Attempt 22/1024:
Starting point: [0.72030713 0.02725264 0.78327112]
Arrival point: [0.82437376 0.03455007 0.82437152]
check grad: tensor([-6.2938e-05, -3.9672e-05, -1.7734e-04])
tensor(0.0002)
Converged to critical point with ||grad||=1.92e-04 < 1e-05
Point [0.82437376 0.03455007 0.82437152] is too close to existing minimum at [0.82437498 0.03455081 0.82437501] (distance 0.000004 < 0.01)
Point [0.82437376 0.03455007 0.82437152] is too close to existing minimum. Rejecting.

__________________________________________________________________________________________
Attempt 23/1024:
Starting point: [0.92990798 0.52506276 0.31399698]
Arrival point: [0.82437142 0.34181124 0.34181085]
check grad: tensor([-1.8235e-04,  9.2539e-05,  7.2147e-05])
tensor(0.0002)
Converged to critical point with ||grad||=2.17e-04 < 1e-05
Point [0.82437142 0.34181124 0.34181085] is too close to existing minimum at [0.82437499 0.34180945 0.34180945] (distance 0.000004 < 0.01)
Point [0.82437142 0.34181124 0.34181085] is too close to existing minimum. Rejecting.

__________________________________________________________________________________________
Attempt 24/1024:
Starting point: [0.41323831 0.45625346 0.50263296]
Arrival point: [0.34180768 0.34180802 0.34181032]
check grad: tensor([-9.1403e-05, -7.3943e-05,  4.4698e-05])
tensor(0.0001)
Converged to critical point with ||grad||=1.26e-04 < 1e-05
Point [0.34180768 0.34180802 0.34181032] is too close to existing minimum at [0.34180946 0.34180945 0.34180945] (distance 0.000002 < 0.01)
Point [0.34180768 0.34180802 0.34181032] is too close to existing minimum. Rejecting.

__________________________________________________________________________________________
Attempt 25/1024:
Starting point: [0.48225949 0.84148151 0.28394527]
Arrival point: [0.34181267 0.82437377 0.34181187]
check grad: tensor([ 1.6628e-04, -6.2640e-05,  1.2508e-04])
tensor(0.0002)
Converged to critical point with ||grad||=2.17e-04 < 1e-05
Point [0.34181267 0.82437377 0.34181187] is too close to existing minimum at [0.34180945 0.82437499 0.34180945] (distance 0.000004 < 0.01)
Point [0.34181267 0.82437377 0.34181187] is too close to existing minimum. Rejecting.

__________________________________________________________________________________________
Attempt 26/1024:
Starting point: [0.98710375 0.14765648 0.5956758 ]
Arrival point: [0.82437172 0.03455108 0.8243743 ]
check grad: tensor([-1.6738e-04,  1.4504e-05, -3.5522e-05])
tensor(0.0002)
Converged to critical point with ||grad||=1.72e-04 < 1e-05
Point [0.82437172 0.03455108 0.8243743 ] is too close to existing minimum at [0.82437498 0.03455081 0.82437501] (distance 0.000003 < 0.01)
Point [0.82437172 0.03455108 0.8243743 ] is too close to existing minimum. Rejecting.

__________________________________________________________________________________________
Attempt 27/1024:
Starting point: [0.66739914 0.6459401  0.00232472]
Arrival point: [0.82437482 0.82437163 0.03455254]
check grad: tensor([-8.6541e-06, -1.7164e-04,  9.2978e-05])
tensor(0.0002)
Converged to critical point with ||grad||=1.95e-04 < 1e-05
Point [0.82437482 0.82437163 0.03455254] is too close to existing minimum at [0.824375   0.82437499 0.03455081] (distance 0.000004 < 0.01)
Point [0.82437482 0.82437163 0.03455254] is too close to existing minimum. Rejecting.

__________________________________________________________________________________________
Attempt 28/1024:
Starting point: [0.17622595 0.34368617 0.81382447]
Arrival point: [0.34180776 0.34180854 0.82437862]
check grad: tensor([-8.7492e-05, -4.6896e-05,  1.8537e-04])
tensor(0.0002)
Converged to critical point with ||grad||=2.10e-04 < 1e-05
Point [0.34180776 0.34180854 0.82437862] is too close to existing minimum at [0.34180945 0.34180947 0.824375  ] (distance 0.000004 < 0.01)
Point [0.34180776 0.34180854 0.82437862] is too close to existing minimum. Rejecting.

__________________________________________________________________________________________
Attempt 29/1024:
Starting point: [0.11783771 0.61441333 0.72917687]
Arrival point: [0.03455036 0.82437389 0.82437708]
check grad: tensor([-2.4145e-05, -5.6457e-05,  1.0669e-04])
tensor(0.0001)
Converged to critical point with ||grad||=1.23e-04 < 1e-05
Point [0.03455036 0.82437389 0.82437708] is too close to existing minimum at [0.03455081 0.82437499 0.82437499] (distance 0.000002 < 0.01)
Point [0.03455036 0.82437389 0.82437708] is too close to existing minimum. Rejecting.

__________________________________________________________________________________________
Attempt 30/1024:
Starting point: [0.60127375 0.43722085 0.41561528]
Arrival point: [0.82437461 0.34180606 0.34180715]
check grad: tensor([-1.9507e-05, -1.7501e-04, -1.1896e-04])
tensor(0.0002)
Converged to critical point with ||grad||=2.13e-04 < 1e-05
Point [0.82437461 0.34180606 0.34180715] is too close to existing minimum at [0.82437499 0.34180945 0.34180945] (distance 0.000004 < 0.01)
Point [0.82437461 0.34180606 0.34180715] is too close to existing minimum. Rejecting.

__________________________________________________________________________________________
Attempt 31/1024:
Starting point: [0.81062966 0.935504   0.94732169]
Arrival point: [0.82437242 0.82437818 0.8243754 ]
check grad: tensor([-1.3168e-04,  1.6279e-04,  2.0837e-05])
tensor(0.0002)
Converged to critical point with ||grad||=2.10e-04 < 1e-05
Point [0.82437242 0.82437818 0.8243754 ] is too close to existing minimum at [0.82437499 0.82437499 0.82437499] (distance 0.000004 < 0.01)
Point [0.82437242 0.82437818 0.8243754 ] is too close to existing minimum. Rejecting.

__________________________________________________________________________________________
Attempt 32/1024:
Starting point: [0.28227064 0.11661847 0.13399089]
Arrival point: [0.34181286 0.03454961 0.03455207]
check grad: tensor([ 1.7583e-04, -6.4289e-05,  6.7371e-05])
tensor(0.0002)
Converged to critical point with ||grad||=1.99e-04 < 1e-05
Point [0.34181286 0.03454961 0.03455207] is too close to existing minimum at [0.34180945 0.03455081 0.03455081] (distance 0.000004 < 0.01)
Point [0.34181286 0.03454961 0.03455207] is too close to existing minimum. Rejecting.

__________________________________________________________________________________________
Attempt 33/1024:
Starting point: [0.29824527 0.5809358  0.49420927]
Arrival point: [0.3418053  0.82437537 0.34180859]
check grad: tensor([-2.1423e-04,  1.9344e-05, -4.4377e-05])
tensor(0.0002)
Converged to critical point with ||grad||=2.20e-04 < 1e-05
Point [0.3418053  0.82437537 0.34180859] is too close to existing minimum at [0.34180945 0.82437499 0.34180945] (distance 0.000004 < 0.01)
Point [0.3418053  0.82437537 0.34180859] is too close to existing minimum. Rejecting.

__________________________________________________________________________________________
Attempt 34/1024:
Starting point: [0.79538358 0.39892107 0.68083055]
Arrival point: [0.82437684 0.34180641 0.82437503]
check grad: tensor([ 9.4518e-05, -1.5685e-04,  2.0606e-06])
tensor(0.0002)
Converged to critical point with ||grad||=1.83e-04 < 1e-05
Point [0.82437684 0.34180641 0.82437503] is too close to existing minimum at [0.82437499 0.34180945 0.82437499] (distance 0.000004 < 0.01)
Point [0.82437684 0.34180641 0.82437503] is too close to existing minimum. Rejecting.

__________________________________________________________________________________________
Attempt 35/1024:
Starting point: [0.61703856 0.90062266 0.21357005]
Arrival point: [0.8243726  0.8243718  0.34180983]
check grad: tensor([-1.2232e-04, -1.6309e-04,  1.9693e-05])
tensor(0.0002)
Converged to critical point with ||grad||=2.05e-04 < 1e-05
Point [0.8243726  0.8243718  0.34180983] is too close to existing minimum at [0.82437499 0.82437499 0.34180945] (distance 0.000004 < 0.01)
Point [0.8243726  0.8243718  0.34180983] is too close to existing minimum. Rejecting.


In [6]:
# Save to CSV
results_df = save_critical_points_to_csv(minima, maxima, saddles, dimension=DIM, filename="critical_points_schwefel_torch.csv")

results_df = pd.concat((resume_df,results_df), ignore_index=True)

display(results_df)

Saved critical_points_schwefel_torch.csv

          x1        x2        x3       f_value     type
0   0.341809  0.824375  0.824375  2.171397e-01  minimum
1   0.034551  0.034551  0.034551  1.066044e+00  minimum
2   0.034551  0.034551  0.824375  7.106958e-01  minimum
3   0.341809  0.341809  0.341809  6.514190e-01  minimum
4   0.034551  0.824375  0.824375  3.553479e-01  minimum
5   0.341809  0.034551  0.034551  9.278355e-01  minimum
6   0.034551  0.824375  0.034551  7.106958e-01  minimum
7   0.824375  0.341809  0.824375  2.171397e-01  minimum
8   0.341809  0.341809  0.034551  7.896273e-01  minimum
9   0.824375  0.341809  0.341809  4.342794e-01  minimum
10  0.824375  0.824375  0.034551  3.553479e-01  minimum
11  0.341809  0.824375  0.341809  4.342794e-01  minimum
12  0.824375  0.824375  0.341809  2.171397e-01  minimum
13  0.341809  0.341809  0.824375  4.342794e-01  minimum
14  0.034551  0.341809  0.824375  5.724876e-01  minimum
15  0.034551  0.034551  0.341809  9.278355e-01  minimum
16  0.034551  0.341809  0.341809  7.896273e-01  minimum
17  0.824375  0.341809  0.034551  5.724876e-01  minimum
18  0.341809  0.034551  0.824375  5.724876e-01  minimum
19  0.824375  0.824375  0.824375  3.820000e-08  minimum
20  0.034551  0.824375  0.341809  5.724876e-01  minimum
21  0.341809  0.034551  0.341809  7.896273e-01  minimum
22  0.824375  0.034551  0.034551  7.106958e-01  minimum
23  0.341809  0.824375  0.034551  5.724876e-01  minimum
24  0.824375  0.034551  0.341809  5.724876e-01  minimum
25  0.824375  0.034551  0.824375  3.553479e-01  minimum
26  0.034551  0.341810  0.034551  9.278355e-01  minimum