In [29]:
import sys
import torch
MODULEPATH="../../"
sys.path.append(MODULEPATH)
sys.path.append('../')

from critical_points.torch_critical_point_finder import find_critical_points_torch, save_critical_points_to_csv
from test_schwefel.schwefel_function_nnmodule import Schwefel3D, schwefel_loss  # your existing module
import pandas as pd

In [30]:
model_builder = lambda p: Schwefel3D(*p)

In [31]:
# Set parameters
BOUNDS = {'x1': (0.0, 1.0), 'x2': (0.0, 1.0), 'x3': (0.0, 1.0)}
DIM = 3
ATTEMPTS = 8
MIN_DISTANCE = 0.01

In [35]:
try:
    resume_df = pd.read_csv("critical_points_schwefel_torch3d.csv", index_col=0)
    display(resume_df)
except FileNotFoundError:
    resume_df = None

         x1        x2        x3   f_value     type  index
0  0.034551  0.341810  0.034551  0.089870  minimum      0
1  0.561167  0.824375  0.561167  0.601089   saddle      2
2  0.824375  0.034551  0.561167  0.236910   saddle      1
3  0.561167  0.561167  0.824375  0.601089   saddle      2
4  0.166287  0.561167  0.341810  0.640560   saddle      2
5  0.561167  0.341809  0.824375  0.098701   saddle      1
6  0.824375  0.824375  0.166287 -0.296107   saddle      1

In [36]:
# Run search
minima, maxima, saddles = find_critical_points_torch(
    model_builder=model_builder,
    loss_func=schwefel_loss,
    input = [],             # placeholder model input for compatibility (Schwefel model has no model input)
    bounds=BOUNDS,
    dimension=DIM,
    num_attempts=ATTEMPTS,
    min_distance=MIN_DISTANCE,
    device="cpu",
    lr=5e-2,
    max_iter=5_000,
    resume_df=resume_df,
    seed=1101
)

Loaded 7 valid minima from dataframe.
Resuming with 7 loaded points.

__________________________________________________________________________________________
Attempt 1/8:
Starting point: [0.25317813 0.88321528 0.5628975 ]
learning rate 0.05
Converged after 256 iterations.
Arrival point: [0.56116667 0.8243751  0.56116653]
check grad: tensor([-7.8352e-06,  5.6196e-06, -1.7612e-07], grad_fn=<CatBackward0>)
Reject: True

__________________________________________________________________________________________
Attempt 2/8:
Starting point: [0.77770659 0.06539727 0.25324407]
learning rate 0.05
Converged after 248 iterations.
Arrival point: [0.82437487 0.03455089 0.56116662]
check grad: tensor([-6.6945e-06,  4.5265e-06, -5.3740e-06], grad_fn=<CatBackward0>)
Reject: True

__________________________________________________________________________________________
Attempt 3/8:
Starting point: [0.56835509 0.56319261 0.84452757]
learning rate 0.05
Converged after 227 iterations.
Arrival point: [0.56116658 0.56116654 0.82437516]
check grad: tensor([-3.2391e-06, -9.1250e-07,  9.0072e-06], grad_fn=<CatBackward0>)
Reject: True

__________________________________________________________________________________________
Attempt 4/8:
Starting point: [0.08874842 0.38493165 0.03510112]
learning rate 0.05
Converged after 246 iterations.
Arrival point: [0.03455093 0.34180958 0.03455081]
check grad: tensor([6.8310e-06, 6.9404e-06, 9.7834e-08], grad_fn=<CatBackward0>)
Reject: True

__________________________________________________________________________________________
Attempt 5/8:
Starting point: [0.1467218  0.65715037 0.38284267]
learning rate 0.05
Converged after 254 iterations.
Arrival point: [0.16628742 0.56116668 0.34180953]
check grad: tensor([ 2.1401e-06, -8.4234e-06,  4.4109e-06], grad_fn=<CatBackward0>)
Reject: True

__________________________________________________________________________________________
Attempt 6/8:
Starting point: [0.63391115 0.35395075 0.69847755]
learning rate 0.05
Converged after 255 iterations.
Arrival point: [0.56116665 0.34180947 0.82437486]
check grad: tensor([-6.8135e-06,  1.3076e-06, -7.1902e-06], grad_fn=<CatBackward0>)
Reject: True

__________________________________________________________________________________________
Attempt 7/8:
Starting point: [0.95362088 0.85174561 0.16468831]
learning rate 0.05
Converged after 256 iterations.
Arrival point: [0.82437516 0.82437504 0.16628746]
check grad: tensor([9.1926e-06, 2.7488e-06, 1.6533e-07], grad_fn=<CatBackward0>)
Reject: True

__________________________________________________________________________________________
Attempt 8/8:
Starting point: [0.45275785 0.15886722 0.98009621]
learning rate 0.05
Out of bounds at 0 iterations.
Arrival point: [0.55210082 0.15924355 1.12470726]
check grad: tensor([3.5955, 0.3837, 4.9908], grad_fn=<CatBackward0>)

In [37]:
# Save to CSV
results_df = save_critical_points_to_csv(minima, maxima, saddles, dimension=DIM, filename="critical_points_schwefel_torch3d.csv")

results_df = pd.concat((resume_df,results_df), ignore_index=True)

display(results_df)

Saved critical_points_schwefel_torch3d.csv

         x1        x2        x3   f_value     type  index
0  0.034551  0.341810  0.034551  0.089870  minimum      0
1  0.561167  0.824375  0.561167  0.601089   saddle      2
2  0.824375  0.034551  0.561167  0.236910   saddle      1
3  0.561167  0.561167  0.824375  0.601089   saddle      2
4  0.166287  0.561167  0.341810  0.640560   saddle      2
5  0.561167  0.341809  0.824375  0.098701   saddle      1
6  0.824375  0.824375  0.166287 -0.296107   saddle      1