In [2]:
import sys
import torch
MODULEPATH="../../"
sys.path.append(MODULEPATH)
sys.path.append('../')

from critical_points.torch_critical_point_finder import find_critical_points_torch, save_critical_points_to_csv
from test_schwefel.schwefel_function_nnmodule import Schwefel4D, schwefel_loss  # your existing module
import pandas as pd

In [3]:
model_builder = lambda p: Schwefel4D(*p)

In [8]:
# Set parameters
BOUNDS = {'x1': (0.0, 1.0), 'x2': (0.0, 1.0), 'x3': (0.0, 1.0), 'x4':(0.0,1.0)}
DIM = 4
ATTEMPTS = 16
MIN_DISTANCE = 0.01

In [9]:
try:
    resume_df = pd.read_csv("critical_points_schwefel_torch4d.csv", index_col=0)
    display(resume_df)
except FileNotFoundError:
    resume_df = None

         x1        x2        x3        x4   f_value     type  index
0  0.824375  0.824375  0.341809  0.341810 -0.822669  minimum      0
1  0.561167  0.824375  0.561167  0.824375  0.182106   saddle      2
2  0.824375  0.034551  0.166288  0.341809 -0.142602   saddle      1
3  0.561167  0.561166  0.824375  0.824375  0.182106   saddle      2
4  0.166287  0.341810  0.341810  0.034551  0.074538   saddle      1
5  0.034551  0.824375  0.034551  0.166287 -0.004394   saddle      1
6  0.561166  0.341809  0.824375  0.561167  0.399246   saddle      2
7  0.341810  0.166288  0.824375  0.824375 -0.497950   saddle      1

In [10]:
# Run search
minima, maxima, saddles = find_critical_points_torch(
    model_builder=model_builder,
    loss_func=schwefel_loss,
    input = [],             # placeholder model input for compatibility (Schwefel model has no model input)
    bounds=BOUNDS,
    dimension=DIM,
    num_attempts=ATTEMPTS,
    min_distance=MIN_DISTANCE,
    device="cpu",
    lr=5e-2,
    max_iter=5_000,
    resume_df=resume_df,
    seed=1101
)

Loaded 8 valid minima from dataframe.
Resuming with 8 loaded points.

__________________________________________________________________________________________
Attempt 1/16:
Starting point: [0.25317813 0.88321528 0.5628975  0.93463721]
learning rate 0.05
Converged after 262 iterations.
Arrival point: [0.56116663 0.82437507 0.56116653 0.82437511]
check grad: tensor([-5.7596e-06,  4.1309e-06, -1.2947e-07,  6.4498e-06],
       grad_fn=<CatBackward0>)
Reject: True

__________________________________________________________________________________________
Attempt 2/16:
Starting point: [0.81004849 0.02864734 0.19346821 0.32005931]
learning rate 0.05
Converged after 238 iterations.
Arrival point: [0.82437492 0.03455078 0.16628758 0.34180935]
check grad: tensor([-3.6235e-06, -1.5582e-06, -6.8664e-06, -5.4129e-06],
       grad_fn=<CatBackward0>)
Reject: True

__________________________________________________________________________________________
Attempt 3/16:
Starting point: [0.63891078 0.52521363 0.75115956 0.6992202 ]
learning rate 0.05
Converged after 260 iterations.
Arrival point: [0.56116663 0.56116647 0.82437489 0.82437488]
check grad: tensor([-5.5146e-06,  2.8185e-06, -5.2137e-06, -5.7780e-06],
       grad_fn=<CatBackward0>)
Reject: True

__________________________________________________________________________________________
Attempt 4/16:
Starting point: [0.17188589 0.38762555 0.38218421 0.05339159]
learning rate 0.05
Converged after 247 iterations.
Arrival point: [0.16628748 0.34180958 0.34180956 0.03455087]
check grad: tensor([-9.2205e-07,  6.9406e-06,  6.2277e-06,  3.1072e-06],
       grad_fn=<CatBackward0>)
Reject: True

__________________________________________________________________________________________
Attempt 5/16:
Starting point: [0.04076806 0.71229063 0.07882508 0.18113785]
learning rate 0.05
Converged after 254 iterations.
Arrival point: [0.03455082 0.82437483 0.03455089 0.16628749]
check grad: tensor([ 7.3533e-07, -8.7551e-06,  4.2302e-06, -1.6974e-06],
       grad_fn=<CatBackward0>)
Reject: True

__________________________________________________________________________________________
Attempt 6/16:
Starting point: [0.52296211 0.32457964 0.70972898 0.56622354]
learning rate 0.05
Converged after 254 iterations.
Arrival point: [0.56116645 0.34180942 0.82437483 0.56116653]
check grad: tensor([ 4.0485e-06, -1.9081e-06, -8.7600e-06, -5.7045e-07],
       grad_fn=<CatBackward0>)
Reject: True

__________________________________________________________________________________________
Attempt 7/16:
Starting point: [0.91089098 0.82114689 0.26751826 0.44573157]
learning rate 0.05
Converged after 258 iterations.
Arrival point: [0.82437512 0.82437499 0.34180936 0.34180953]
check grad: tensor([ 6.8756e-06, -2.9486e-07, -4.8191e-06,  4.5178e-06],
       grad_fn=<CatBackward0>)
Reject: True

__________________________________________________________________________________________
Attempt 8/16:
Starting point: [0.40135527 0.21669994 0.8979682  0.79956798]
learning rate 0.05
Converged after 257 iterations.
Arrival point: [0.34180954 0.16628754 0.82437511 0.82437495]
check grad: tensor([ 5.0973e-06, -4.2948e-06,  6.4233e-06, -2.3392e-06],
       grad_fn=<CatBackward0>)
Reject: True

__________________________________________________________________________________________
Attempt 9/16:
Starting point: [0.45224712 0.56330884 0.33534835 0.50831123]
learning rate 0.05
Converged after 244 iterations.
Arrival point: [0.56116658 0.56116653 0.34180943 0.56116636]
check grad: tensor([-3.2589e-06, -4.0344e-07, -1.2168e-06,  8.8924e-06],
       grad_fn=<CatBackward0>)
Reject: False
Type: saddle

__________________________________________________________________________________________
Attempt 10/16:
Starting point: [0.98549516 0.45889337 0.9541673  0.23650581]
learning rate 0.05
Out of bounds at 0 iterations.
Arrival point: [1.04035144 0.48724902 0.93354343 0.2273047 ]
check grad: tensor([ 4.9739,  3.5706,  4.8600, -2.7825], grad_fn=<CatBackward0>)

__________________________________________________________________________________________
Attempt 11/16:
Starting point: [0.56484364 0.95451362 0.0216151  0.8687261 ]
learning rate 0.05
Converged after 257 iterations.
Arrival point: [0.56116653 0.82437515 0.03455079 0.82437507]
check grad: tensor([-3.5558e-07,  8.7349e-06, -1.2475e-06,  4.1404e-06],
       grad_fn=<CatBackward0>)
Reject: False
Type: saddle

__________________________________________________________________________________________
Attempt 12/16:
Starting point: [0.12143761 0.06671203 0.64095665 0.37817186]
learning rate 0.05
Converged after 255 iterations.
Arrival point: [0.16628739 0.03455087 0.56116666 0.34180952]
check grad: tensor([ 3.9316e-06,  3.2644e-06, -7.2465e-06,  3.7644e-06],
       grad_fn=<CatBackward0>)
Reject: False
Type: saddle

__________________________________________________________________________________________
Attempt 13/16:
Starting point: [0.22451742 0.76745286 0.82004632 0.26263058]
learning rate 0.05
Converged after 254 iterations.
Arrival point: [0.16628756 0.82437488 0.82437498 0.34180934]
check grad: tensor([-5.4655e-06, -5.8360e-06, -4.8519e-07, -5.8961e-06],
       grad_fn=<CatBackward0>)
Reject: False
Type: saddle

__________________________________________________________________________________________
Attempt 14/16:
Starting point: [0.71470497 0.12977227 0.4392645  0.99049065]
learning rate 0.05
Out of bounds at 0 iterations.
Arrival point: [0.72964198 0.13221091 0.41747165 1.02524828]
check grad: tensor([-4.1332,  1.6673,  3.5527,  4.9448], grad_fn=<CatBackward0>)

__________________________________________________________________________________________
Attempt 15/16:
Starting point: [0.85214383 0.62539348 0.50682811 0.12304282]
learning rate 0.05
Converged after 254 iterations.
Arrival point: [0.82437505 0.56116664 0.56116642 0.16628739]
check grad: tensor([ 3.0890e-06, -6.5427e-06,  5.4405e-06,  4.0521e-06],
       grad_fn=<CatBackward0>)
Reject: False
Type: saddle

__________________________________________________________________________________________
Attempt 16/16:
Starting point: [0.33461044 0.27085509 0.12552367 0.63215169]
learning rate 0.05
Converged after 254 iterations.
Arrival point: [0.34180944 0.34180934 0.16628739 0.56116665]
check grad: tensor([-8.1105e-07, -5.8567e-06,  3.9057e-06, -7.0489e-06],
       grad_fn=<CatBackward0>)
Reject: False
Type: saddle

In [11]:
# Save to CSV
results_df = save_critical_points_to_csv(minima, maxima, saddles, dimension=DIM, filename="critical_points_schwefel_torch4d.csv")

results_df = pd.concat((resume_df,results_df), ignore_index=True)

display(results_df)

Saved critical_points_schwefel_torch4d.csv

          x1        x2        x3        x4   f_value     type  index
0   0.824375  0.824375  0.341809  0.341810 -0.822669  minimum      0
1   0.561167  0.824375  0.561167  0.824375  0.182106   saddle      2
2   0.824375  0.034551  0.166288  0.341809 -0.142602   saddle      1
3   0.561167  0.561166  0.824375  0.824375  0.182106   saddle      2
4   0.166287  0.341810  0.341810  0.034551  0.074538   saddle      1
5   0.034551  0.824375  0.034551  0.166287 -0.004394   saddle      1
6   0.561166  0.341809  0.824375  0.561167  0.399246   saddle      2
7   0.341810  0.166288  0.824375  0.824375 -0.497950   saddle      1
8   0.561167  0.561167  0.341809  0.561166  1.118773   saddle      3
9   0.561167  0.824375  0.034551  0.824375 -0.182073   saddle      1
10  0.166287  0.034551  0.561167  0.341810  0.576925   saddle      2
11  0.166288  0.824375  0.824375  0.341809 -0.497950   saddle      1
12  0.824375  0.561167  0.561166  0.166287  0.723965   saddle      3
13  0.341809  0.341809  0.166287  0.561167  0.438717   saddle      2